version: '3'

services:
  banco-clientes:
    image: postgres:12.6
    container_name: banco-clientes
    restart: unless-stopped
    environment:
      POSTGRES_DB: clientes-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "3535:5432"
    networks:
      - teste-network
  
  django_clientes:
        container_name: django_clientes
        restart: unless-stopped
        environment:
          DJANGO_SETTINGS_MODULE: 'sistemaClientes.settings'
        build: 
          context: .
          dockerfile: Dockerfile
    
        command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
          - .:/code
        ports:
          - "8000:8000"
        depends_on:
          - banco-clientes
        networks:
          - teste-network

networks:
  teste-network:
    driver: bridge