# Generated by Django 3.2.7 on 2021-09-19 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairros',
            fields=[
                ('id_bairro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_bairro', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Bairros',
                'ordering': ['nome_bairro'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('email', models.CharField(max_length=80)),
                ('data_nascimento', models.DateField()),
                ('observacoes', models.TextField(blank=True, max_length=4000, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_id_user', to=settings.AUTH_USER_MODEL)),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pais', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'paises',
                'db_table': 'Paises',
                'ordering': ['nome_pais'],
            },
        ),
        migrations.CreateModel(
            name='Ufs',
            fields=[
                ('id_uf', models.AutoField(primary_key=True, serialize=False)),
                ('nome_uf', models.CharField(max_length=30)),
                ('sigla_uf', models.CharField(max_length=2)),
                ('regiao', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'Ufs',
                'ordering': ['sigla_uf'],
            },
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=8)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('tel1', models.CharField(max_length=15)),
                ('observacoes', models.TextField(blank=True, max_length=10000, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('id_bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientesApp.bairros')),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientesApp.clientes')),
                ('id_user_alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Endereços',
                'db_table': 'Enderecos',
                'ordering': ['logradouro'],
            },
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cidade', models.CharField(max_length=50)),
                ('id_uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientesApp.ufs')),
            ],
            options={
                'db_table': 'Cidades',
                'ordering': ['nome_cidade'],
            },
        ),
        migrations.AddField(
            model_name='bairros',
            name='id_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientesApp.cidades'),
        ),
    ]


